version: "3.9"

services:
  database_rent:
    image: postgres
    container_name: database_rent
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentalx
      - POSTGRES_DB=rentalx
    volumes: 
      - pgdata:/data/postgress
  app:
    build: .
    volumes: 
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
